# Generated by Django 5.1 on 2024-09-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icon_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iconcategorymodel',
            old_name='value',
            new_name='icon_category_title',
        ),
        migrations.RenameField(
            model_name='iconsmodel',
            old_name='category',
            new_name='icon_category',
        ),
        migrations.RenameField(
            model_name='iconsmodel',
            old_name='code',
            new_name='icon_code',
        ),
        migrations.RenameField(
            model_name='iconsmodel',
            old_name='name',
            new_name='icon_name',
        ),
    ]
