# Generated by Django 5.1 on 2024-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon_app', '0002_rename_value_iconcategorymodel_icon_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconcategorymodel',
            name='icon_category_title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='iconsmodel',
            name='icon_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
