# Generated by Django 5.1 on 2024-09-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon_app', '0003_alter_iconcategorymodel_icon_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconsmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='iconsmodel',
            name='icon_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
