# Generated by Django 5.1 on 2024-09-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='ttile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
