# Generated by Django 5.1 on 2024-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_ttile_taskmodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_all_day_long',
            field=models.BooleanField(default=False),
        ),
    ]
