# Generated by Django 5.1 on 2024-09-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_taskmodel_is_all_day_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='is_all_day_long',
            field=models.BooleanField(),
        ),
    ]
