# Generated by Django 5.1 on 2024-09-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon_app', '0004_remove_iconsmodel_id_alter_iconsmodel_icon_code'),
        ('todo', '0004_alter_taskmodel_is_all_day_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='icon_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icon_app.iconsmodel'),
        ),
    ]
