# Generated by Django 5.1 on 2024-09-15 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0004_alter_categorymodel_title_and_more'),
        ('todo', '0005_taskmodel_icon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories_app.categorymodel'),
        ),
    ]
