# Generated by Django 5.1 on 2024-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_taskmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='reminder_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
