# Generated by Django 5.1 on 2024-09-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_taskmodel_is_reminder_taskmodel_reminder_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='reminder_time',
            field=models.TimeField(null=True),
        ),
    ]
