# Generated by Django 5.1 on 2024-09-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_taskmodel_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_long_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='todo.taskmodel'),
        ),
    ]
