# Generated by Django 5.1 on 2024-09-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_taskmodel_is_long_task_taskmodel_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
