# Generated by Django 5.1 on 2024-09-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_tasksteps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksteps',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
