# Generated by Django 5.1 on 2024-09-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_rename_completed_tasksteps_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='end_time',
            new_name='finish_time',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='start_time',
            new_name='sbegin_time',
        ),
        migrations.CreateModel(
            name='TaskActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('progress_rate', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='TaskSteps',
        ),
    ]
