# Generated by Django 5.1 on 2024-09-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_rename_end_time_taskmodel_finish_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='sbegin_time',
            new_name='begin_time',
        ),
    ]
