# Generated by Django 5.1 on 2024-09-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_rename_sbegin_time_taskmodel_begin_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_reminder',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='reminder_note',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='reminder_time',
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_note', models.CharField(blank=True, max_length=100)),
                ('reminderEnabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.taskmodel')),
            ],
        ),
    ]
