# Generated by Django 5.1 on 2024-09-21 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_remove_taskmodel_is_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='progressState',
            field=models.CharField(choices=[('notstarted', 'NotStarted'), ('ongoing', 'Ongoing'), ('pending', 'Pending'), ('completed', 'Completed')], default='notstarted', max_length=15),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='is_unstructured_task',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
