# Generated by Django 5.1 on 2024-09-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_taskactionitem_created_on_taskactionitem_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_all_day_long',
        ),
    ]
