# Generated by Django 5.1 on 2024-09-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_remove_taskmodel_is_all_day_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactionitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='todo.taskmodel'),
        ),
        migrations.AlterField(
            model_name='taskreminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='todo.taskmodel'),
        ),
    ]
