# Generated by Django 5.1 on 2024-09-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_taskactionitem_task_alter_taskreminder_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecurranceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('recurrurance_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=15)),
                ('recurrurance_data', models.JSONField(default=dict)),
                ('repeat_forever', models.BooleanField(default=False)),
                ('repeat_end_date', models.DateField(null=True)),
                ('repeat_count', models.PositiveBigIntegerField(default=0)),
                ('is_auto_extend', models.BooleanField(default=False)),
                ('effective_date', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_recurrance', to='todo.taskmodel')),
            ],
            options={
                'ordering': ['effective_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('begin_time', models.TimeField(null=True)),
                ('finish_time', models.TimeField(null=True)),
                ('is_all_day_long', models.BooleanField(default=False)),
                ('progress_rate', models.PositiveSmallIntegerField(default=0)),
                ('progressState', models.CharField(choices=[('notstarted', 'NotStarted'), ('ongoing', 'Ongoing'), ('pending', 'Pending'), ('completed', 'Completed')], default='notstarted', max_length=15)),
                ('recurrance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub_parts', to='todo.taskrecurrancemodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_sub_parts', to='todo.taskmodel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TaskSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('progress_rate', models.PositiveSmallIntegerField(default=0)),
                ('order', models.PositiveIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='todo.tasksubparts')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
