# Generated by Django 5.1 on 2024-09-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_taskrecurrancemodel_tasksubparts_tasksteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecurrancemodel',
            name='effective_date',
            field=models.DateTimeField(null=True),
        ),
    ]
