# Generated by Django 5.1 on 2024-09-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_taskrecurrancemodel_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreminder',
            name='reminder_time',
            field=models.TimeField(),
        ),
    ]
