# Generated by Django 5.1 on 2024-09-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_taskreminder_reminder_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubparts',
            old_name='begin_time',
            new_name='start_time',
        ),
    ]
