# Generated by Django 5.1 on 2024-09-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_rename_begin_time_tasksubparts_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubparts',
            old_name='finish_time',
            new_name='end_time',
        ),
    ]
