# Generated by Django 5.1 on 2024-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_rename_finish_time_tasksubparts_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrecurrancemodel',
            name='total_repeats',
            field=models.IntegerField(default=1),
        ),
    ]
