# Generated by Django 5.1 on 2024-09-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_taskrecurrancemodel_total_repeats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecurrancemodel',
            name='recurrurance_type',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekly_times', 'Weekly_Times'), ('monthly', 'Monthly'), ('monthly_times', 'Monthly_Times')], default='once', max_length=15),
        ),
    ]
