# Generated by Django 5.1 on 2024-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_alter_taskrecurrancemodel_recurrurance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksteps',
            name='task_steps_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
