# Generated by Django 5.1 on 2024-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_tasksteps_task_steps_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksteps',
            name='task_steps_id',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
