# Generated by Django 5.1 on 2024-09-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icon_app', '0004_remove_iconsmodel_id_alter_iconsmodel_icon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('task', 'Task')], max_length=10)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('icon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icon_app.iconsmodel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories_app.globalcategorymodel')),
            ],
            options={
                'verbose_name': 'Global Category',
                'verbose_name_plural': 'Global Categories',
            },
        ),
    ]
