# Generated by Django 5.1 on 2024-09-15 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0002_categorymodel'),
        ('icon_app', '0004_remove_iconsmodel_id_alter_iconsmodel_icon_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categorymodel',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_user_category'),
        ),
    ]
