# Generated by Django 5.1 on 2024-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_app', '0003_categorymodel_unique_user_category'),
        ('icon_app', '0004_remove_iconsmodel_id_alter_iconsmodel_icon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='globalcategorymodel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='globalcategorymodel',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_global_category'),
        ),
    ]
